apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-context-claim
  # namespace: playground
spec:
  accessModes:
    - ReadOnlyMany
    #- ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: context-storage # ищем по имени класса
  #volumeName: dockerfile #ищем по имени волума